add_executable(smoke_test smoke_test.cc)
target_link_libraries(smoke_test PRIVATE GTest::gtest_main)
add_test(NAME smoke COMMAND smoke_test)

add_subdirectory(util)
add_subdirectory(queue)  
add_subdirectory(proto)    
add_subdirectory(book)     
add_subdirectory(net)      
add_subdirectory(engine)   
